version: "2.0"

services:
  postgres:
    image: postgres:9.6.5-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=8neEmdvl
    volumes:
      - ./docker-persistence/postgres:/var/lib/postgresql/data
      - ./conf/postgresql.conf:/etc/postgresql.conf
    command: postgres -c config_file=/etc/postgresql.conf

  app:
    build: .
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./docker-persistence/app-data/git-data:/app/git-data
      - ./docker-persistence/app-data/log:/app/log
      - ./conf/app.conf:/app/conf/app.conf
    depends_on:
      - postgres
